package com.alex.study.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alex.study.gdao.bean.DnjConversation;
import com.alex.study.gdao.bean.DnjMessage;

import com.alex.study.greendao.DnjConversationDao;
import com.alex.study.greendao.DnjMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dnjConversationDaoConfig;
    private final DaoConfig dnjMessageDaoConfig;

    private final DnjConversationDao dnjConversationDao;
    private final DnjMessageDao dnjMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dnjConversationDaoConfig = daoConfigMap.get(DnjConversationDao.class).clone();
        dnjConversationDaoConfig.initIdentityScope(type);

        dnjMessageDaoConfig = daoConfigMap.get(DnjMessageDao.class).clone();
        dnjMessageDaoConfig.initIdentityScope(type);

        dnjConversationDao = new DnjConversationDao(dnjConversationDaoConfig, this);
        dnjMessageDao = new DnjMessageDao(dnjMessageDaoConfig, this);

        registerDao(DnjConversation.class, dnjConversationDao);
        registerDao(DnjMessage.class, dnjMessageDao);
    }
    
    public void clear() {
        dnjConversationDaoConfig.clearIdentityScope();
        dnjMessageDaoConfig.clearIdentityScope();
    }

    public DnjConversationDao getDnjConversationDao() {
        return dnjConversationDao;
    }

    public DnjMessageDao getDnjMessageDao() {
        return dnjMessageDao;
    }

}
